### ISSUE TITLE
MathJax 2.5 menu is transparent in IE11 enterprise mode

### ISSUE THREAD

**Issue by NSoiffer** [mathjax/MathJax-website#26] opened 2015-02-25 22:18 UTC
The MJ menu for 2.5 has changed in a way that makes it really hard to use in IE11 in Enterprise Mode (IE8 emulation). This use to work in 2.4 and earlier (I think onemathematicalcat.org uses an older release and it look fine there). I realize you don't want to support IE8, but I would think it isn't a big deal to allow the menu to continue to work ok.

Here's a picture of what I see on http://meta.math.stackexchange.com/questions/5020/mathjax-basic-tutorial-and-quick-reference:
![mathjaxmenu](https://cloud.githubusercontent.com/assets/1545836/6381772/bb2152c6-bcf8-11e4-9803-e105c0c8b122.png)

**Comment by dpvc** [comment] 2015-02-25 22:34
There was no change in the rendering code for the menus between 2.4 and 2.5.  I suspect CSS bleed through may be the cause.  Does this happen on this [sample page](http://cdn.mathjax.org/mathjax/latest/test/sample-tex.html) as well?

**Comment by NSoiffer** [comment] 2015-02-25 22:51
Yes, it happens there as well.

**Comment by dpvc** [comment] 2015-02-25 23:12
OK, I'm able to reproduce.  Apparently it is a bug in the IE8 emulation mode of IE>8, as the menus work fine in actual IE8 on XP and Windows 7.  It first appears in v2.4, and there was a restructuring of the menu code in that version that seems to be the culprit.  There is a line that sets the menu width explicitly (based on its current width).  I don't remember the reason for that, though it has always been there; the difference in 2.4 is that the menu items are added to the menu first and then the menu added to the page, while in 2.3 and below the menu container is added to the page then the items are added.  Apparently the IE8 emulation mode gets the offsetWidth as 0 in the first case but not the second, so MathJax sets the width to a small width, giving the effect you are seeing.

For your own pages, you can use

```
<style>
  #MathJax_Menu {width: auto ! important}
</style>
```

as a temporary work-around.

**Comment by dpvc** [comment] 2015-02-25 23:18
I started issue mathjax/MathJax#1069 to handle this (as it is really a MathJax issue, not a MathJax-website issue).

**Comment by NSoiffer** [comment] 2015-02-26 07:17
Thanks for looking into this. It's not a big deal in the grand scheme of
things, but since I use emulation mode all the time for MathPlayer, it
really makes life difficult for me for trying out MathJax pages with
MathPlayer.

```
Neil
```

On Wed, Feb 25, 2015 at 3:12 PM, Davide P. Cervone <notifications@github.com

**Comment by pkra** [comment] 2015-02-26 07:33
Closing the issue here.

**Closed as completed by pkra** 2015-02-26 07:33 UTC
Labels: upstream
